[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.16.0"


[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "frame-ancestors 'self' https://storenotify.in https://successrate.netlify.app http://fyersbook.netlify.app http://localhost:8888 http://localhost:4200 https://atmdemoaivenmysql.onrender.com https://rzp.io https://store-stocks.netlify.app https://fyersmarketfeed.onrender.com"
     X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "index"
    Cache-Control = "public, max-age=0, no-cache, no-store, must-revalidate"

[dev]
  bind = "0.0.0.0"  # Bind to all available network interfaces
  framework = "#custom"
  command = "npm run dev"   # Or your actual dev command
  port = 8888               # Optional
  targetPort = 3000         # Optional if using a proxy
  https = { keyFile = "./ssl.key/server.key", certFile = "./ssl.crt/server.crt" }
#  https = true
#  cert = "./ssl.crt/server.crt"
#  key = "./ssl.key/server.key"

[[headers]]
for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://storenotify.in, https://sheer-maryjo-storenotify-4c573750.koyeb.app, https://successrate.netlify.app, http://localhost:4200, http://localhost:3450, http://localhost:8888, http://fyersbook.netlify.app, https://storenotiftycom.netlify.app, https://atmdemoaivenmysql.onrender.com, https://rzp.io https://store-stocks.netlify.app https://fyersmarketfeed.onrender.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"


 

[[edge_functions]]
function = "netlifystockedgestream"
path = "/fyersticker"